// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Osu20XXML.Model
{
    public class ModelInput
    {
        [ColumnName("year"), LoadColumn(0)]
        public string Year { get; set; }


        [ColumnName("hp"), LoadColumn(1)]
        public float Hp { get; set; }


        [ColumnName("cs"), LoadColumn(2)]
        public float Cs { get; set; }


        [ColumnName("od"), LoadColumn(3)]
        public float Od { get; set; }


        [ColumnName("ar"), LoadColumn(4)]
        public float Ar { get; set; }


        [ColumnName("avgDeltaTime"), LoadColumn(5)]
        public float AvgDeltaTime { get; set; }


        [ColumnName("stddevDeltaTime"), LoadColumn(6)]
        public float StddevDeltaTime { get; set; }


        [ColumnName("diffVariance"), LoadColumn(7)]
        public float DiffVariance { get; set; }


    }
}
